DROP TABLE IF EXISTS TBL_TASK;

CREATE TABLE TBL_TASK (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    task_name VARCHAR(250) NOT NULL,
    task_description VARCHAR(250) NOT NULL,
    employee_id INT
);


DROP TABLE IF EXISTS TBL_EMPLOYEE;

CREATE TABLE TBL_EMPLOYEE (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL
);



ALTER TABLE TBL_TASK
ADD FOREIGN KEY (employee_id)
REFERENCES TBL_EMPLOYEE(id)